version: '2'
services:
  oauth2proxy:
    image: jsimonovski/oauth2-proxy
    labels:
      io.rancher.scheduler.affinity: app_host
      io.rancher.container.pull_image: always
      io.rancher.container.network: true
      traefik.enable: true
      traefik.frontend.rule: Host:logs.teampirate.io
      traefik.port: 4180
    environment:
      EMAIL_DOMAIN: ${email_domain}
      UPSTREAM_SERVICE_URL: ${upstream_service_url}
      COOKIE_SECRET: ${cookie_secret}
      CLIENT_ID: ${client_id}
      CLIENT_SECRET: ${client_secret}