version: 2
catalog:
  name: Ghost
  version: v0.2-teampirate
  upgrade_from: v0.1-educaas
  description: Blog powered by Ghost. Requires no database
  questions:
    - variable: blog_url
      label: Blog URL
      required: true
      type: string
    - variable: traefik_route_rule
      label: Traefik Routing Rule
      description: In Case you want to route multiple URLs to ghost
      required: false
      type: string
    - variable: efs_location
      label: EFS Location
      description: /mnt/efs/rancher/ghost/${location}
      required: true
      default: blog
      type: string